services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - ENVIRONMENT=docker
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=django_diary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    command: >
      sh -c "uv run python manage.py tailwind start &
             uv run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=django_diary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume: