# Generated by Django 3.2.25 on 2025-06-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
    ]
