# Generated by Django 3.2.25 on 2025-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_comment_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='画像'),
        ),
    ]
